# Generated by Django 2.0.3 on 2019-01-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='input_id',
            field=models.IntegerField(default=0),
        ),
    ]
