# Generated by Django 2.0.3 on 2019-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0002_input_input_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
