# Generated by Django 2.0.3 on 2019-01-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0003_auto_20190109_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_email',
            field=models.CharField(default='user@example.com', max_length=60),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user_name',
            field=models.CharField(max_length=60),
        ),
    ]
