# Generated by Django 2.0.3 on 2019-01-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palindrome', '0004_auto_20190109_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDetails',
            new_name='UserDetail',
        ),
    ]
